import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from 'next/link';
import { LogoContainer } from './_components/layout/logo';
import { Logo } from '@/src/components/logo';
import { AnimatedThemeToggler } from '@/src/components/magicui/animated-theme-toggler';
import { ColorPicker } from '@/src/components/color-picker';

import "./globals.css";
import { ThemeProvider } from "next-themes";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: 'device-width',
  height: 'device-height',
  initialScale: 1,
  minimumScale: 1,
  maximumScale: 1,
  userScalable: false,
  themeColor: [
    { media: '(prefers-color-scheme: dark)', color: '#090909' },
    { media: '(prefers-color-scheme: light)', color: 'white' },
  ],
};

export default async function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

  <ThemeProvider
                    attribute="class"
                    defaultTheme="light"
                    storageKey="xplace-theme"
                    enableSystem={true}
                  >
                    <div className="h-screen flex flex-col overflow-hidden">
                      <header className="fixed top-0 left-0 right-0 w-full flex flex-col pt-4 pb-2 justify-center bg-card z-50 border-b border-zinc-200 dark:border-zinc-800">
                        <div className="flex items-center justify-between w-full px-2 md:px-6 h-10">
                          <div className="pl-8 md:pl-8 flex items-center gap-2 md:gap-3">
                            <LogoContainer>
                              <Link href="/" prefetch={false}>
                                <Logo className="size-full aspect-square" />
                              </Link>
                            </LogoContainer>
                            <div>
                              <h1 className="text-2xl font-bold text-zinc-900 dark:text-zinc-100">
                                x402/place
                              </h1>
                              <p className="text-sm text-zinc-600 dark:text-zinc-400">
                                Collaborative pixel canvas
                              </p>
                            </div>
                          </div>
                          <div className="flex items-center gap-1 md:gap-2">
                            <ColorPicker />
                            {/* <AnimatedThemeToggler /> */}
                          </div>
                        </div>
                      </header>
                      <div className="bg-background flex-1 flex flex-col overflow-hidden">
                        {children}
                      </div>
                    </div>
                  </ThemeProvider>
      </body>
    </html>
  );
}
